library:
  source-dirs: src
  dependencies:
  - parsec
  - mtl
tests:
  interpreter-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HUnit
    - hspec
    - interpreter
copyright: 2018 Ciliz
maintainer: example@example.com
dependencies:
- containers
- base >= 4.7 && < 5
name: interpreter
version: 0.2.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Ciliz
github: https://github.com/vladimir-brezgunov/fp-newbies/tree/master/interpreter
license: BSD3
executables:
  interpreter-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - interpreter
description: Please see the README on GitHub at <https://github.com/vladimir-brezgunov/fp-newbies/tree/master/interpreter#readme>
